/**
 * Firestore Security Rules Test Suite — "Dirty Dozen" Payload Verification
 * Validates that all 12 adversarial payloads in security_spec.md return PERMISSION_DENIED.
 */

export interface SecurityTestVector {
  id: number;
  name: string;
  collection: string;
  operation: 'create' | 'update' | 'delete' | 'get' | 'list';
  auth: { uid: string; email: string; email_verified: boolean } | null;
  docId: string;
  existingData?: Record<string, unknown>;
  incomingData?: Record<string, unknown>;
  expectedResult: 'PERMISSION_DENIED';
}

export const DIRTY_DOZEN_VECTORS: SecurityTestVector[] = [
  {
    id: 1,
    name: 'Identity Spoofing on Create',
    collection: 'dcrRequests',
    operation: 'create',
    auth: { uid: 'attacker_uid_111', email: 'attacker@example.com', email_verified: true },
    docId: 'dcr_001',
    incomingData: {
      ownerId: 'victim_uid_999',
      dcrNumber: 'DCR-2026-001',
      requestType: 'ADD',
      docCode: 'SOP-QA-001',
      docTitle: 'Quality Manual',
      department: 'Quality Assurance',
      isoClause: 'Clause 7.5',
      currentRevision: 'None',
      proposedRevision: 'Rev 1.0',
      justification: 'Required for certification',
      draftContent: 'Initial normative content',
      isDraftCompleted: false,
      status: 'DRAFT',
      requesterName: 'Attacker',
      qmgReviewerName: 'Pending QMG',
      qmgComments: 'Awaiting submission',
      requestDate: '2026-10-08',
      requestYear: 2026,
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Unverified Email Spoof Attack on Admin',
    collection: 'documents',
    operation: 'get',
    auth: { uid: 'spoof_uid', email: 'itdecode7@gmail.com', email_verified: false },
    docId: 'doc_001',
    existingData: { ownerId: 'other_user_uid' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Shadow Field Injection on Create',
    collection: 'documents',
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'doc_001',
    incomingData: {
      ownerId: 'user_1',
      docCode: 'SOP-QA-001',
      title: 'Document Control Procedure',
      department: 'Quality Assurance',
      isoClause: 'ISO 9001 Clause 7.5',
      revision: 'Rev 1.0',
      status: 'ACTIVE',
      effectiveDate: '2026-10-08',
      authorName: 'Jane Doe',
      approverName: 'QMG Lead',
      summary: 'Standard operating procedure for document control.',
      isSuperVerified: true,
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'Shadow Field Injection on Update',
    collection: 'dcrRequests',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'dcr_001',
    existingData: { status: 'DRAFT', ownerId: 'user_1' },
    incomingData: { status: 'PENDING_QMG', ownerId: 'user_1', bypassQmg: true },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'Terminal State Mutation on Approved DCR',
    collection: 'dcrRequests',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'dcr_001',
    existingData: { status: 'APPROVED', ownerId: 'user_1' },
    incomingData: { status: 'DRAFT', ownerId: 'user_1' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Terminal State Mutation on Cancelled Document',
    collection: 'documents',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'doc_001',
    existingData: { status: 'CANCELLED', ownerId: 'user_1' },
    incomingData: { status: 'ACTIVE', ownerId: 'user_1' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Immutable Audit Log Tampering',
    collection: 'changeLogs',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'log_001',
    existingData: { ownerId: 'user_1', actionType: 'ADDED' },
    incomingData: { ownerId: 'user_1', actionType: 'CANCELLED' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Client Timestamp Forgery',
    collection: 'dcrRequests',
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'dcr_002',
    incomingData: {
      ownerId: 'user_1',
      createdAt: '1999-01-01T00:00:00Z',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Immortal Field Mutation on Update',
    collection: 'documents',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'doc_001',
    existingData: { ownerId: 'user_1', docCode: 'SOP-QA-001', status: 'ACTIVE' },
    incomingData: { ownerId: 'user_2', docCode: 'SOP-QA-999', status: 'ACTIVE' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Denial of Wallet / Oversized String Poisoning',
    collection: 'dcrRequests',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'dcr_001',
    existingData: { ownerId: 'user_1', status: 'DRAFT' },
    incomingData: { ownerId: 'user_1', status: 'DRAFT', justification: 'A'.repeat(10000) },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Path ID Poisoning',
    collection: 'documents',
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: 'invalid$id!with*spaces',
    incomingData: { ownerId: 'user_1' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Unauthorized Cross-Tenant List Scrape',
    collection: 'dcrRequests',
    operation: 'list',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    docId: '*',
    existingData: { ownerId: 'user_2' },
    expectedResult: 'PERMISSION_DENIED',
  },
];
